### ISSUE TITLE
Add step to installation instructions

### ISSUE THREAD

**Issue by mwhardesty** [irmantas/symfony2-vagrant#31]
- run vagrant (for the first time it should take up to 10-15 min) $ vagrant up
- Web server is accessible with http://33.33.33.100 (IP address can be changed in Vagrantfile)

Between the two steps above, I was prompted for a password. So, an additional step could be added:
- You may be prompted for a password. This is for an admin account w/ sudo access. 

^ At least in my case.

**Comment by bizmate** [comment]
This is quite standard for nfs shares - https://github.com/irmantas/symfony2-vagrant/blob/master/Vagrantfile#L11 . Also you can add it in a PR

**Comment by mwhardesty** [comment]
Thanks for the tip. Learn something everyday, right?
